services:
  mangarr:
    build:
      context: .
      dockerfile: Dockerfile
    image: mangarr:latest
    ports:
      - 3737:3737
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    restart: unless-stopped
