[versions]
jvmTarget = "21"
buildConfig_version = "5.7.1"
shadowJar_version = "9.2.2"
ktlint_version = "1.7.1"

kotlin_version = "2.2.21"
kodein_version = "7.30.0"
okhttp_version = "4.12.0"
grpc_version = "1.75.0"
protoc_version = "4.32.0"
dex2jar_version = "2.4.32"
serialization_version = "1.9.0"
xml_serialization_version = "0.91.3"


[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin_version" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.7.3" }

koin = { module = "io.insert-koin:koin-core", version = "4.1.1" }
kaml = { module = "com.charleskorn.kaml:kaml", version = "0.61.0" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp_version" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp_version" }
okhttp-brotli = { module = "com.squareup.okhttp3:okhttp-brotli", version.ref = "okhttp_version" }
okhttp-dnsoverhttps = { module = "com.squareup.okhttp3:okhttp-dnsoverhttps", version.ref = "okhttp_version" }

kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version = "7.0.13" }
logstash-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version = "8.0"}

grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc_version" }
grpc-protobuf-lite = { module = "io.grpc:grpc-protobuf-lite", version.ref = "grpc_version" }
grpc-netty = { module = "io.grpc:grpc-netty", version.ref = "grpc_version" }
grpc-okhttp = { module = "io.grpc:grpc-okhttp",version.ref = "grpc_version" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc_version" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version = "1.4.3" }

protoc = { module = "com.google.protobuf:protoc", version.ref = "protoc_version" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protoc_version" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protoc_version" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protoc_version" }
protoc-gen-grpc-java = { module = "io.grpc:protoc-gen-grpc-java", version = "1.75.0" }
protoc-gen-grpc-kotlin = { module = "io.grpc:protoc-gen-grpc-kotlin", version = "1.4.3" }

injekt = { module = "com.github.mihonapp:injekt", version = "91edab2317" }
kcef = { module = "dev.datlag:kcef", version = "2025.03.23"}
bouncycastle = "org.bouncycastle:bcprov-jdk18on:1.82"
rxjava = { module = "io.reactivex:rxjava", version = "1.3.8" }
jsoup = { module = "org.jsoup:jsoup", version = "1.21.2" }

asm = "org.ow2.asm:asm:9.8"
dex2jar-tools = { module = "de.femtopedia.dex2jar:dex-tools", version.ref = "dex2jar_version" }
dex2jar-translator = { module = "de.femtopedia.dex2jar:dex-translator", version.ref = "dex2jar_version" }
apk-parser = "net.dongliu:apk-parser:2.6.10"
apksig = "com.android.tools.build:apksig:8.13.1"

serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization_version" }
serialization-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "serialization_version" }
serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization_version" }
serialization-xml-core = { module = "io.github.pdvrieze.xmlutil:core-android", version.ref = "xml_serialization_version" }
serialization-xml = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xml_serialization_version" }

[plugins]
buildConfig = { id = "com.github.gmazzo.buildconfig", version= "5.7.1"}
shadowjar = { id = "com.gradleup.shadow", version = "9.2.2" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin_version" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "14.0.1" }
protobuf = { id = "com.google.protobuf", version = "0.9.5" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin_version" }


[bundles]
kotlin = ["kotlin-stdlib", "kotlin-coroutines"]
logging = ["kotlin-logging", "logstash-encoder"]
network = ["okhttp", "okhttp-logging", "okhttp-brotli", "okhttp-dnsoverhttps", "rxjava"]
# logging = ["kotlin-logging", "slf4j-simple"]
grpc = ["grpc-protobuf", "grpc-protobuf-lite", "grpc-netty", "grpc-stub", "grpc-kotlin-stub", "protoc", "protobuf-kotlin", "protobuf-kotlin-lite", "protobuf-java-util", "protoc-gen-grpc-java", "protoc-gen-grpc-kotlin"]
tachiyomi = ["injekt", "kcef", "bouncycastle", "rxjava", "jsoup"]
apk = ["asm", "dex2jar-tools", "dex2jar-translator", "apk-parser", "apksig"]
serialization = ["serialization-json", "serialization-json-okio", "serialization-protobuf", "serialization-xml-core", "serialization-xml"]
